[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
solana_nft_anchor = "98zYx4PAUJqDgZBWgTx8V2KtaKy2sKCxD5cQbBNdJkU5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://quiet-young-pallet.solana-devnet.quiknode.pro/3404df0b4463b4a85ae6781e7161814488e44918/"
wallet = "/home/levi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
